# Generated by Django 4.1.5 on 2023-02-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=64)),
                ('user_id', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64)),
                ('discriminator', models.CharField(max_length=4)),
                ('credits', models.IntegerField()),
            ],
        ),
    ]
